package com.aok.b2b.member.dao;

import com.aok.b2b.member.entity.SmsSend;
import com.aok.b2b.member.entity.SmsSendExample;
import com.aok.framework.mybatis.repository.BaseMybatisDao;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsSendMapper extends BaseMybatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_smssend
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    int countByExample(SmsSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_smssend
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    int deleteByExample(SmsSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_smssend
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_smssend
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    int insert(SmsSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_smssend
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    int insertSelective(SmsSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_smssend
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    List<SmsSend> selectByExample(SmsSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_smssend
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    SmsSend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_smssend
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsSend record, @Param("example") SmsSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_smssend
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    int updateByExample(@Param("record") SmsSend record, @Param("example") SmsSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_smssend
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    int updateByPrimaryKeySelective(SmsSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_smssend
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    int updateByPrimaryKey(SmsSend record);
}