package com.doct.common.entity.usercenter;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExendExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public UserExendExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIsNull() {
            addCriterion("user is null");
            return (Criteria) this;
        }

        public Criteria andUserIsNotNull() {
            addCriterion("user is not null");
            return (Criteria) this;
        }

        public Criteria andUserEqualTo(Long value) {
            addCriterion("user =", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotEqualTo(Long value) {
            addCriterion("user <>", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserGreaterThan(Long value) {
            addCriterion("user >", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserGreaterThanOrEqualTo(Long value) {
            addCriterion("user >=", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLessThan(Long value) {
            addCriterion("user <", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLessThanOrEqualTo(Long value) {
            addCriterion("user <=", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserIn(List<Long> values) {
            addCriterion("user in", values, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotIn(List<Long> values) {
            addCriterion("user not in", values, "user");
            return (Criteria) this;
        }

        public Criteria andUserBetween(Long value1, Long value2) {
            addCriterion("user between", value1, value2, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotBetween(Long value1, Long value2) {
            addCriterion("user not between", value1, value2, "user");
            return (Criteria) this;
        }

        public Criteria andSignIsNull() {
            addCriterion("sign is null");
            return (Criteria) this;
        }

        public Criteria andSignIsNotNull() {
            addCriterion("sign is not null");
            return (Criteria) this;
        }

        public Criteria andSignEqualTo(String value) {
            addCriterion("sign =", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotEqualTo(String value) {
            addCriterion("sign <>", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThan(String value) {
            addCriterion("sign >", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThanOrEqualTo(String value) {
            addCriterion("sign >=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThan(String value) {
            addCriterion("sign <", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThanOrEqualTo(String value) {
            addCriterion("sign <=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLike(String value) {
            addCriterion("sign like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotLike(String value) {
            addCriterion("sign not like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignIn(List<String> values) {
            addCriterion("sign in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotIn(List<String> values) {
            addCriterion("sign not in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignBetween(String value1, String value2) {
            addCriterion("sign between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotBetween(String value1, String value2) {
            addCriterion("sign not between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andImagePathIsNull() {
            addCriterion("image_path is null");
            return (Criteria) this;
        }

        public Criteria andImagePathIsNotNull() {
            addCriterion("image_path is not null");
            return (Criteria) this;
        }

        public Criteria andImagePathEqualTo(String value) {
            addCriterion("image_path =", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotEqualTo(String value) {
            addCriterion("image_path <>", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathGreaterThan(String value) {
            addCriterion("image_path >", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathGreaterThanOrEqualTo(String value) {
            addCriterion("image_path >=", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathLessThan(String value) {
            addCriterion("image_path <", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathLessThanOrEqualTo(String value) {
            addCriterion("image_path <=", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathLike(String value) {
            addCriterion("image_path like", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotLike(String value) {
            addCriterion("image_path not like", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathIn(List<String> values) {
            addCriterion("image_path in", values, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotIn(List<String> values) {
            addCriterion("image_path not in", values, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathBetween(String value1, String value2) {
            addCriterion("image_path between", value1, value2, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotBetween(String value1, String value2) {
            addCriterion("image_path not between", value1, value2, "imagePath");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0IsNull() {
            addCriterion("attribute_value0 is null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0IsNotNull() {
            addCriterion("attribute_value0 is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0EqualTo(String value) {
            addCriterion("attribute_value0 =", value, "attributeValue0");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0NotEqualTo(String value) {
            addCriterion("attribute_value0 <>", value, "attributeValue0");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0GreaterThan(String value) {
            addCriterion("attribute_value0 >", value, "attributeValue0");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0GreaterThanOrEqualTo(String value) {
            addCriterion("attribute_value0 >=", value, "attributeValue0");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0LessThan(String value) {
            addCriterion("attribute_value0 <", value, "attributeValue0");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0LessThanOrEqualTo(String value) {
            addCriterion("attribute_value0 <=", value, "attributeValue0");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0Like(String value) {
            addCriterion("attribute_value0 like", value, "attributeValue0");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0NotLike(String value) {
            addCriterion("attribute_value0 not like", value, "attributeValue0");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0In(List<String> values) {
            addCriterion("attribute_value0 in", values, "attributeValue0");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0NotIn(List<String> values) {
            addCriterion("attribute_value0 not in", values, "attributeValue0");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0Between(String value1, String value2) {
            addCriterion("attribute_value0 between", value1, value2, "attributeValue0");
            return (Criteria) this;
        }

        public Criteria andAttributeValue0NotBetween(String value1, String value2) {
            addCriterion("attribute_value0 not between", value1, value2, "attributeValue0");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1IsNull() {
            addCriterion("attribute_value1 is null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1IsNotNull() {
            addCriterion("attribute_value1 is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1EqualTo(String value) {
            addCriterion("attribute_value1 =", value, "attributeValue1");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1NotEqualTo(String value) {
            addCriterion("attribute_value1 <>", value, "attributeValue1");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1GreaterThan(String value) {
            addCriterion("attribute_value1 >", value, "attributeValue1");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1GreaterThanOrEqualTo(String value) {
            addCriterion("attribute_value1 >=", value, "attributeValue1");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1LessThan(String value) {
            addCriterion("attribute_value1 <", value, "attributeValue1");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1LessThanOrEqualTo(String value) {
            addCriterion("attribute_value1 <=", value, "attributeValue1");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1Like(String value) {
            addCriterion("attribute_value1 like", value, "attributeValue1");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1NotLike(String value) {
            addCriterion("attribute_value1 not like", value, "attributeValue1");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1In(List<String> values) {
            addCriterion("attribute_value1 in", values, "attributeValue1");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1NotIn(List<String> values) {
            addCriterion("attribute_value1 not in", values, "attributeValue1");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1Between(String value1, String value2) {
            addCriterion("attribute_value1 between", value1, value2, "attributeValue1");
            return (Criteria) this;
        }

        public Criteria andAttributeValue1NotBetween(String value1, String value2) {
            addCriterion("attribute_value1 not between", value1, value2, "attributeValue1");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2IsNull() {
            addCriterion("attribute_value2 is null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2IsNotNull() {
            addCriterion("attribute_value2 is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2EqualTo(String value) {
            addCriterion("attribute_value2 =", value, "attributeValue2");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2NotEqualTo(String value) {
            addCriterion("attribute_value2 <>", value, "attributeValue2");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2GreaterThan(String value) {
            addCriterion("attribute_value2 >", value, "attributeValue2");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2GreaterThanOrEqualTo(String value) {
            addCriterion("attribute_value2 >=", value, "attributeValue2");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2LessThan(String value) {
            addCriterion("attribute_value2 <", value, "attributeValue2");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2LessThanOrEqualTo(String value) {
            addCriterion("attribute_value2 <=", value, "attributeValue2");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2Like(String value) {
            addCriterion("attribute_value2 like", value, "attributeValue2");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2NotLike(String value) {
            addCriterion("attribute_value2 not like", value, "attributeValue2");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2In(List<String> values) {
            addCriterion("attribute_value2 in", values, "attributeValue2");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2NotIn(List<String> values) {
            addCriterion("attribute_value2 not in", values, "attributeValue2");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2Between(String value1, String value2) {
            addCriterion("attribute_value2 between", value1, value2, "attributeValue2");
            return (Criteria) this;
        }

        public Criteria andAttributeValue2NotBetween(String value1, String value2) {
            addCriterion("attribute_value2 not between", value1, value2, "attributeValue2");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3IsNull() {
            addCriterion("attribute_value3 is null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3IsNotNull() {
            addCriterion("attribute_value3 is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3EqualTo(String value) {
            addCriterion("attribute_value3 =", value, "attributeValue3");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3NotEqualTo(String value) {
            addCriterion("attribute_value3 <>", value, "attributeValue3");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3GreaterThan(String value) {
            addCriterion("attribute_value3 >", value, "attributeValue3");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3GreaterThanOrEqualTo(String value) {
            addCriterion("attribute_value3 >=", value, "attributeValue3");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3LessThan(String value) {
            addCriterion("attribute_value3 <", value, "attributeValue3");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3LessThanOrEqualTo(String value) {
            addCriterion("attribute_value3 <=", value, "attributeValue3");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3Like(String value) {
            addCriterion("attribute_value3 like", value, "attributeValue3");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3NotLike(String value) {
            addCriterion("attribute_value3 not like", value, "attributeValue3");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3In(List<String> values) {
            addCriterion("attribute_value3 in", values, "attributeValue3");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3NotIn(List<String> values) {
            addCriterion("attribute_value3 not in", values, "attributeValue3");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3Between(String value1, String value2) {
            addCriterion("attribute_value3 between", value1, value2, "attributeValue3");
            return (Criteria) this;
        }

        public Criteria andAttributeValue3NotBetween(String value1, String value2) {
            addCriterion("attribute_value3 not between", value1, value2, "attributeValue3");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4IsNull() {
            addCriterion("attribute_value4 is null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4IsNotNull() {
            addCriterion("attribute_value4 is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4EqualTo(String value) {
            addCriterion("attribute_value4 =", value, "attributeValue4");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4NotEqualTo(String value) {
            addCriterion("attribute_value4 <>", value, "attributeValue4");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4GreaterThan(String value) {
            addCriterion("attribute_value4 >", value, "attributeValue4");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4GreaterThanOrEqualTo(String value) {
            addCriterion("attribute_value4 >=", value, "attributeValue4");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4LessThan(String value) {
            addCriterion("attribute_value4 <", value, "attributeValue4");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4LessThanOrEqualTo(String value) {
            addCriterion("attribute_value4 <=", value, "attributeValue4");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4Like(String value) {
            addCriterion("attribute_value4 like", value, "attributeValue4");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4NotLike(String value) {
            addCriterion("attribute_value4 not like", value, "attributeValue4");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4In(List<String> values) {
            addCriterion("attribute_value4 in", values, "attributeValue4");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4NotIn(List<String> values) {
            addCriterion("attribute_value4 not in", values, "attributeValue4");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4Between(String value1, String value2) {
            addCriterion("attribute_value4 between", value1, value2, "attributeValue4");
            return (Criteria) this;
        }

        public Criteria andAttributeValue4NotBetween(String value1, String value2) {
            addCriterion("attribute_value4 not between", value1, value2, "attributeValue4");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5IsNull() {
            addCriterion("attribute_value5 is null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5IsNotNull() {
            addCriterion("attribute_value5 is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5EqualTo(String value) {
            addCriterion("attribute_value5 =", value, "attributeValue5");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5NotEqualTo(String value) {
            addCriterion("attribute_value5 <>", value, "attributeValue5");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5GreaterThan(String value) {
            addCriterion("attribute_value5 >", value, "attributeValue5");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5GreaterThanOrEqualTo(String value) {
            addCriterion("attribute_value5 >=", value, "attributeValue5");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5LessThan(String value) {
            addCriterion("attribute_value5 <", value, "attributeValue5");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5LessThanOrEqualTo(String value) {
            addCriterion("attribute_value5 <=", value, "attributeValue5");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5Like(String value) {
            addCriterion("attribute_value5 like", value, "attributeValue5");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5NotLike(String value) {
            addCriterion("attribute_value5 not like", value, "attributeValue5");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5In(List<String> values) {
            addCriterion("attribute_value5 in", values, "attributeValue5");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5NotIn(List<String> values) {
            addCriterion("attribute_value5 not in", values, "attributeValue5");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5Between(String value1, String value2) {
            addCriterion("attribute_value5 between", value1, value2, "attributeValue5");
            return (Criteria) this;
        }

        public Criteria andAttributeValue5NotBetween(String value1, String value2) {
            addCriterion("attribute_value5 not between", value1, value2, "attributeValue5");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6IsNull() {
            addCriterion("attribute_value6 is null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6IsNotNull() {
            addCriterion("attribute_value6 is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6EqualTo(String value) {
            addCriterion("attribute_value6 =", value, "attributeValue6");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6NotEqualTo(String value) {
            addCriterion("attribute_value6 <>", value, "attributeValue6");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6GreaterThan(String value) {
            addCriterion("attribute_value6 >", value, "attributeValue6");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6GreaterThanOrEqualTo(String value) {
            addCriterion("attribute_value6 >=", value, "attributeValue6");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6LessThan(String value) {
            addCriterion("attribute_value6 <", value, "attributeValue6");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6LessThanOrEqualTo(String value) {
            addCriterion("attribute_value6 <=", value, "attributeValue6");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6Like(String value) {
            addCriterion("attribute_value6 like", value, "attributeValue6");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6NotLike(String value) {
            addCriterion("attribute_value6 not like", value, "attributeValue6");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6In(List<String> values) {
            addCriterion("attribute_value6 in", values, "attributeValue6");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6NotIn(List<String> values) {
            addCriterion("attribute_value6 not in", values, "attributeValue6");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6Between(String value1, String value2) {
            addCriterion("attribute_value6 between", value1, value2, "attributeValue6");
            return (Criteria) this;
        }

        public Criteria andAttributeValue6NotBetween(String value1, String value2) {
            addCriterion("attribute_value6 not between", value1, value2, "attributeValue6");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7IsNull() {
            addCriterion("attribute_value7 is null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7IsNotNull() {
            addCriterion("attribute_value7 is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7EqualTo(String value) {
            addCriterion("attribute_value7 =", value, "attributeValue7");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7NotEqualTo(String value) {
            addCriterion("attribute_value7 <>", value, "attributeValue7");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7GreaterThan(String value) {
            addCriterion("attribute_value7 >", value, "attributeValue7");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7GreaterThanOrEqualTo(String value) {
            addCriterion("attribute_value7 >=", value, "attributeValue7");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7LessThan(String value) {
            addCriterion("attribute_value7 <", value, "attributeValue7");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7LessThanOrEqualTo(String value) {
            addCriterion("attribute_value7 <=", value, "attributeValue7");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7Like(String value) {
            addCriterion("attribute_value7 like", value, "attributeValue7");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7NotLike(String value) {
            addCriterion("attribute_value7 not like", value, "attributeValue7");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7In(List<String> values) {
            addCriterion("attribute_value7 in", values, "attributeValue7");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7NotIn(List<String> values) {
            addCriterion("attribute_value7 not in", values, "attributeValue7");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7Between(String value1, String value2) {
            addCriterion("attribute_value7 between", value1, value2, "attributeValue7");
            return (Criteria) this;
        }

        public Criteria andAttributeValue7NotBetween(String value1, String value2) {
            addCriterion("attribute_value7 not between", value1, value2, "attributeValue7");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8IsNull() {
            addCriterion("attribute_value8 is null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8IsNotNull() {
            addCriterion("attribute_value8 is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8EqualTo(String value) {
            addCriterion("attribute_value8 =", value, "attributeValue8");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8NotEqualTo(String value) {
            addCriterion("attribute_value8 <>", value, "attributeValue8");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8GreaterThan(String value) {
            addCriterion("attribute_value8 >", value, "attributeValue8");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8GreaterThanOrEqualTo(String value) {
            addCriterion("attribute_value8 >=", value, "attributeValue8");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8LessThan(String value) {
            addCriterion("attribute_value8 <", value, "attributeValue8");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8LessThanOrEqualTo(String value) {
            addCriterion("attribute_value8 <=", value, "attributeValue8");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8Like(String value) {
            addCriterion("attribute_value8 like", value, "attributeValue8");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8NotLike(String value) {
            addCriterion("attribute_value8 not like", value, "attributeValue8");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8In(List<String> values) {
            addCriterion("attribute_value8 in", values, "attributeValue8");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8NotIn(List<String> values) {
            addCriterion("attribute_value8 not in", values, "attributeValue8");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8Between(String value1, String value2) {
            addCriterion("attribute_value8 between", value1, value2, "attributeValue8");
            return (Criteria) this;
        }

        public Criteria andAttributeValue8NotBetween(String value1, String value2) {
            addCriterion("attribute_value8 not between", value1, value2, "attributeValue8");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9IsNull() {
            addCriterion("attribute_value9 is null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9IsNotNull() {
            addCriterion("attribute_value9 is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9EqualTo(String value) {
            addCriterion("attribute_value9 =", value, "attributeValue9");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9NotEqualTo(String value) {
            addCriterion("attribute_value9 <>", value, "attributeValue9");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9GreaterThan(String value) {
            addCriterion("attribute_value9 >", value, "attributeValue9");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9GreaterThanOrEqualTo(String value) {
            addCriterion("attribute_value9 >=", value, "attributeValue9");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9LessThan(String value) {
            addCriterion("attribute_value9 <", value, "attributeValue9");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9LessThanOrEqualTo(String value) {
            addCriterion("attribute_value9 <=", value, "attributeValue9");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9Like(String value) {
            addCriterion("attribute_value9 like", value, "attributeValue9");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9NotLike(String value) {
            addCriterion("attribute_value9 not like", value, "attributeValue9");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9In(List<String> values) {
            addCriterion("attribute_value9 in", values, "attributeValue9");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9NotIn(List<String> values) {
            addCriterion("attribute_value9 not in", values, "attributeValue9");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9Between(String value1, String value2) {
            addCriterion("attribute_value9 between", value1, value2, "attributeValue9");
            return (Criteria) this;
        }

        public Criteria andAttributeValue9NotBetween(String value1, String value2) {
            addCriterion("attribute_value9 not between", value1, value2, "attributeValue9");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("modify_date is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("modify_date is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("modify_date =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("modify_date <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("modify_date >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_date >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("modify_date <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("modify_date <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("modify_date in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("modify_date not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("modify_date between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("modify_date not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(Long value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(Long value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(Long value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(Long value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(Long value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(Long value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<Long> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<Long> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(Long value1, Long value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(Long value1, Long value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table his_user_extend
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 22 14:37:28 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}