package com.doct.common.entity.usercenter;

import com.doct.common.configer.entity.BaseEntity;
import java.util.Date;

public class UserExend extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.id
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.user
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private Long user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.sign
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.memo
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.image_path
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.attribute_value0
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String attributeValue0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.attribute_value1
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String attributeValue1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.attribute_value2
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String attributeValue2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.attribute_value3
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String attributeValue3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.attribute_value4
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String attributeValue4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.attribute_value5
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String attributeValue5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.attribute_value6
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String attributeValue6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.attribute_value7
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String attributeValue7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.attribute_value8
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String attributeValue8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.attribute_value9
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private String attributeValue9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.modify_date
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.create_date
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_user_extend.operator
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    private Long operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.id
     *
     * @return the value of his_user_extend.id
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.id
     *
     * @param id the value for his_user_extend.id
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.user
     *
     * @return the value of his_user_extend.user
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public Long getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.user
     *
     * @param user the value for his_user_extend.user
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setUser(Long user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.sign
     *
     * @return the value of his_user_extend.sign
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.sign
     *
     * @param sign the value for his_user_extend.sign
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.memo
     *
     * @return the value of his_user_extend.memo
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.memo
     *
     * @param memo the value for his_user_extend.memo
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.image_path
     *
     * @return the value of his_user_extend.image_path
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.image_path
     *
     * @param imagePath the value for his_user_extend.image_path
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.attribute_value0
     *
     * @return the value of his_user_extend.attribute_value0
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getAttributeValue0() {
        return attributeValue0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.attribute_value0
     *
     * @param attributeValue0 the value for his_user_extend.attribute_value0
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setAttributeValue0(String attributeValue0) {
        this.attributeValue0 = attributeValue0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.attribute_value1
     *
     * @return the value of his_user_extend.attribute_value1
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getAttributeValue1() {
        return attributeValue1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.attribute_value1
     *
     * @param attributeValue1 the value for his_user_extend.attribute_value1
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setAttributeValue1(String attributeValue1) {
        this.attributeValue1 = attributeValue1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.attribute_value2
     *
     * @return the value of his_user_extend.attribute_value2
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getAttributeValue2() {
        return attributeValue2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.attribute_value2
     *
     * @param attributeValue2 the value for his_user_extend.attribute_value2
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setAttributeValue2(String attributeValue2) {
        this.attributeValue2 = attributeValue2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.attribute_value3
     *
     * @return the value of his_user_extend.attribute_value3
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getAttributeValue3() {
        return attributeValue3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.attribute_value3
     *
     * @param attributeValue3 the value for his_user_extend.attribute_value3
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setAttributeValue3(String attributeValue3) {
        this.attributeValue3 = attributeValue3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.attribute_value4
     *
     * @return the value of his_user_extend.attribute_value4
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getAttributeValue4() {
        return attributeValue4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.attribute_value4
     *
     * @param attributeValue4 the value for his_user_extend.attribute_value4
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setAttributeValue4(String attributeValue4) {
        this.attributeValue4 = attributeValue4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.attribute_value5
     *
     * @return the value of his_user_extend.attribute_value5
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getAttributeValue5() {
        return attributeValue5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.attribute_value5
     *
     * @param attributeValue5 the value for his_user_extend.attribute_value5
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setAttributeValue5(String attributeValue5) {
        this.attributeValue5 = attributeValue5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.attribute_value6
     *
     * @return the value of his_user_extend.attribute_value6
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getAttributeValue6() {
        return attributeValue6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.attribute_value6
     *
     * @param attributeValue6 the value for his_user_extend.attribute_value6
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setAttributeValue6(String attributeValue6) {
        this.attributeValue6 = attributeValue6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.attribute_value7
     *
     * @return the value of his_user_extend.attribute_value7
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getAttributeValue7() {
        return attributeValue7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.attribute_value7
     *
     * @param attributeValue7 the value for his_user_extend.attribute_value7
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setAttributeValue7(String attributeValue7) {
        this.attributeValue7 = attributeValue7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.attribute_value8
     *
     * @return the value of his_user_extend.attribute_value8
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getAttributeValue8() {
        return attributeValue8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.attribute_value8
     *
     * @param attributeValue8 the value for his_user_extend.attribute_value8
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setAttributeValue8(String attributeValue8) {
        this.attributeValue8 = attributeValue8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.attribute_value9
     *
     * @return the value of his_user_extend.attribute_value9
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public String getAttributeValue9() {
        return attributeValue9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.attribute_value9
     *
     * @param attributeValue9 the value for his_user_extend.attribute_value9
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setAttributeValue9(String attributeValue9) {
        this.attributeValue9 = attributeValue9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.modify_date
     *
     * @return the value of his_user_extend.modify_date
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.modify_date
     *
     * @param modifyDate the value for his_user_extend.modify_date
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.create_date
     *
     * @return the value of his_user_extend.create_date
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.create_date
     *
     * @param createDate the value for his_user_extend.create_date
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_user_extend.operator
     *
     * @return the value of his_user_extend.operator
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_user_extend.operator
     *
     * @param operator the value for his_user_extend.operator
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }
}