package com.doct.member.dao;

import com.doct.common.entity.usercenter.UserExend;
import com.doct.common.entity.usercenter.UserExendExample;
import com.doct.framework.mybatis.repository.BaseMybatisDao;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserExendMapper extends BaseMybatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    int countByExample(UserExendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    int deleteByExample(UserExendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    int insert(UserExend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    int insertSelective(UserExend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    List<UserExend> selectByExample(UserExendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    UserExend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserExend record, @Param("example") UserExendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    int updateByExample(@Param("record") UserExend record, @Param("example") UserExendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    int updateByPrimaryKeySelective(UserExend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table his_user_extend
     *
     * @mbggenerated Mon Aug 22 14:37:28 CST 2016
     */
    int updateByPrimaryKey(UserExend record);
}