package com.aok.b2b.member.entity;

import com.aok.common.configer.entity.BaseEntity;

public class SmsSend extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_smssend.type
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_smssend.mobiles
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    private String mobiles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_smssend.content
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_smssend.priority
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_smssend.count
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_smssend.status
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_smssend.descr
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_smssend.user
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    private Long user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_smssend.type
     *
     * @return the value of his_smssend.type
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_smssend.type
     *
     * @param type the value for his_smssend.type
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_smssend.mobiles
     *
     * @return the value of his_smssend.mobiles
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public String getMobiles() {
        return mobiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_smssend.mobiles
     *
     * @param mobiles the value for his_smssend.mobiles
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public void setMobiles(String mobiles) {
        this.mobiles = mobiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_smssend.content
     *
     * @return the value of his_smssend.content
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_smssend.content
     *
     * @param content the value for his_smssend.content
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_smssend.priority
     *
     * @return the value of his_smssend.priority
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_smssend.priority
     *
     * @param priority the value for his_smssend.priority
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_smssend.count
     *
     * @return the value of his_smssend.count
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_smssend.count
     *
     * @param count the value for his_smssend.count
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_smssend.status
     *
     * @return the value of his_smssend.status
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_smssend.status
     *
     * @param status the value for his_smssend.status
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_smssend.descr
     *
     * @return the value of his_smssend.descr
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_smssend.descr
     *
     * @param descr the value for his_smssend.descr
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_smssend.user
     *
     * @return the value of his_smssend.user
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public Long getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_smssend.user
     *
     * @param user the value for his_smssend.user
     *
     * @mbggenerated Tue Aug 16 15:15:08 CST 2016
     */
    public void setUser(Long user) {
        this.user = user;
    }
}